# Generated by Django 6.0.2 on 2026-02-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='patronymic',
            field=models.DateField(blank=True, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
