# Generated by Django 6.0.2 on 2026-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passport_data',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
