# Generated by Django 6.0.2 on 2026-02-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_users_phone_number_users_second_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='passport_data',
        ),
    ]
