# Generated by Django 6.0.2 on 2026-02-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_users_passport_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='age',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='second_phone_number',
        ),
    ]
