# Generated by Django 6.0.2 on 2026-02-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_users_age_remove_users_mail_remove_users_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
    ]
