# Generated by Django 6.0.2 on 2026-02-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
