# Generated by Django 6.0.2 on 2026-02-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
