# Generated by Django 6.0.2 on 2026-02-18 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='Автор'),
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('de', 'Немецкий'), ('fr', 'Французский'), ('es', 'Испанский'), ('other', 'Другой')], default='ru', max_length=20, verbose_name='Язык'),
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='for_kids',
            field=models.BooleanField(default=False, verbose_name='Детская литература'),
        ),
        migrations.AddField(
            model_name='book',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Бестселлер'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемое'),
        ),
        migrations.AddField(
            model_name='book',
            name='limited_edition',
            field=models.BooleanField(default=False, verbose_name='Лимитированное издание'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество экземпляров'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('limited', 'Ограниченное количество'), ('out', 'Нет в наличии'), ('expected', 'Ожидается')], default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Художественная литература'), ('nonfiction', 'Нон-фикшн'), ('science', 'Научная литература'), ('fantasy', 'Фэнтези'), ('detective', 'Детектив'), ('romance', 'Роман'), ('poetry', 'Поэзия'), ('children', 'Детская литература'), ('history', 'История'), ('biography', 'Биография'), ('other', 'Другое')], default='', max_length=50, verbose_name='Жанр'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
