# Generated by Django 6.0.2 on 2026-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_book_author_remove_bookinstance_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_file',
        ),
        migrations.AddField(
            model_name='book',
            name='book_content',
            field=models.CharField(blank=True, null=True, verbose_name='Файл книги'),
        ),
    ]
