# Generated by Django 6.0.2 on 2026-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_book_book_file_book_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Файл книги'),
        ),
    ]
